pipeline {
    agent {
        docker {
            image 'abdul46/maven-docker-agent:v1'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "abdul46/spring-boot-dashboard"
        IMAGE_TAG = "${BUILD_NUMBER}"
        SONAR_URL = "http://34.195.20.40:9000"
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('java-spring-dashboard') {
                    sh 'mvn clean package'
                }
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Static Code Analysis') {
            steps {
                dir('java-spring-dashboard') {
                    withCredentials([string(credentialsId: 'sonar', variable: 'SONAR_AUTH_TOKEN')]) {
                        sh '''
                        mvn sonar:sonar \
                        -Dsonar.login=$SONAR_AUTH_TOKEN \
                        -Dsonar.host.url=$SONAR_URL
                        '''
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('java-spring-dashboard') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                    }
                }
            }
        }

        stage('Update K8s Manifest (GitOps)') {
            steps {
                dir('java-spring-dashboard/spring-boot-app-manifests') {
                    sh """
                    sed -i 's|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|' deployment.yml
                    """
                }

                withCredentials([usernamePassword(
                    credentialsId: 'git-cred',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_PASS'
                )]) {
                    sh """
                    git config user.email "ci@jenkins.local"
                    git config user.name "Jenkins CI"
                    git add .
                    git commit -m "Update image to ${IMAGE_TAG}" || echo "No changes"
                    git push https://${GIT_USER}:${GIT_PASS}@github.com/Abdulsam46/Jenkins-CICD-Project.git HEAD:main
                    """
                }
            }
        }
    }

    post {
        success {
            echo "Build ${BUILD_NUMBER} deployed successfully"
        }
        failure {
            echo "Build failed. Check logs."
        }
        always {
            cleanWs()
        }
    }
}
