pipeline {
  agent {
    docker {
      image 'abdul46/maven-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
    }
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
          cd java-spring-dashboard
          mvn clean package -Dorg.slf4j.simpleLogger.defaultLogLevel=error
        '''
      }
    }

    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://34.195.20.40:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonar', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
            cd java-spring-dashboard
            mvn -q -B -ntp sonar:sonar \
            -Dsonar.login=$SONAR_AUTH_TOKEN \
            -Dsonar.host.url=$SONAR_URL
          '''
        }
      }
    }

    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "abdul46/spring-boot-dashboard:latest"
      }
      steps {
        script {
          sh '''
            cd java-spring-dashboard
            docker build -t ${DOCKER_IMAGE} .
          '''
          docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
            docker.image("${DOCKER_IMAGE}").push()
          }
        }
      }
    }

    stage('Update Deployment File') {
	  environment {
        GIT_REPO_NAME = "Jenkins-CICD-Project"
        GIT_USER_NAME = "Abdulsam46"
      }
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
        dir(env.WORKSPACE) {
        sh '''
          git config --global --add safe.directory "$WORKSPACE"
          git config user.email "abdul@test.com"
          git config user.name "Abdul"

          cd java-spring-dashboard/spring-boot-app-manifests/
          sed -i "s/latest/latest/g" deployment.yml

          git add deployment.yml
          git commit -m "Update image to ${BUILD_NUMBER}"
          git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
        '''
         }
        }
      }
    }
  }
}
